# Base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app
EXPOSE 5000

# SDK image for building the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS publish
WORKDIR /

# Copy csproj and restore as distinct layers to cache them
COPY ./Wishlist/Wishlist.csproj ./Wishlist/Wishlist.csproj

WORKDIR /Wishlist
RUN dotnet restore 

# Copy everything else and build
WORKDIR /
COPY . .

WORKDIR /Wishlist
RUN dotnet publish -c Release -o /app/publish

# Final stage / image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_HTTP_PORTS=
ENTRYPOINT ["dotnet", "Wishlist.dll"]