FROM node:18-alpine as build
WORKDIR /app/src
COPY ./Wishlist/Angular/package.json ./Wishlist/Angular/package-lock.json ./
RUN npm i
COPY ./Wishlist/Angular/ .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/src/dist/angular ./
CMD node server/server.mjs
EXPOSE 4000